require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

pod 'FBSDKLoginKit'

target 'LimeFront' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'LimeFrontTests' do
    inherit! :complete
    # Pods for testing
  end

  #use_flipper!({ 'Flipper' => '0.74.0' })
  #  post_install do |installer|
  #      flipper_post_install(installer)
  #  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
end
